package domain

import (
	"fmt"
	"regexp"

	apperrors "github.com/Andryshazzz/go_pet/internal/core/errors"
)

// UninitializedID is used for new users before they are persisted.
// The database generates the real ID on insert.
const UninitializedID = ""

// User represents a user entity in the system.
//
// Fields:
//   - ID: unique identifier (UUID string, empty for new users)
//   - FullName: user's full name (2-100 characters)
//   - PhoneNumber: optional phone number in international format (+79991234567)
type User struct {
	ID          string
	FullName    string
	PhoneNumber *string
}

// NewUser creates a User with the given ID.
// Use this when loading an existing user from the database.
func NewUser(
	id string,
	fullName string,
	phoneNumber *string,
) User {
	return User{
		ID:          id,
		FullName:    fullName,
		PhoneNumber: phoneNumber,
	}

}

// NewUninitializedUser creates a User without an ID.
// Use this when creating a new user before persistence.
// The ID will be generated by the database or application.
func NewUninitializedUser(
	fullName string,
	phoneNumber *string,
) User {
	return NewUser(
		UninitializedID,
		fullName,
		phoneNumber,
	)
}

// Validate checks that the user data meets business rules.
// Returns an error if any field is invalid.
//
// Rules:
//   - FullName: 2-100 characters
//   - PhoneNumber (optional): 10-15 digits, optionally starting with +
func (u *User) Validate() error {
	fullNameLength := len([]rune(u.FullName))
	if fullNameLength < 2 || fullNameLength > 100 {
		return fmt.Errorf(
			"invalid `fullName` len: %d: %w",
			fullNameLength,
			apperrors.ErrInvalidArgument,
		)
	}

	if u.PhoneNumber != nil {
		PhoneNumberLenght := len([]rune(*u.PhoneNumber))
		if PhoneNumberLenght < 10 || PhoneNumberLenght > 15 {
			return fmt.Errorf(
				"invalid `PhoneNumber` len: %d: %w",
				fullNameLength,
				apperrors.ErrInvalidArgument,
			)
		}

		re := regexp.MustCompile(`^\+[0-9]+$`)

		if !re.MatchString(*u.PhoneNumber) {
			return fmt.Errorf(
				"invalid `PhoneNumber` format: %d: %w",
				PhoneNumberLenght,
				apperrors.ErrInvalidArgument,
			)
		}
	}

	return nil
}
