services:
  deploy-app:
    build:
      context: ${AUTH_SERVICE_ROOT}
      dockerfile: ${AUTH_SERVICE_ROOT}/Dockerfile
    container_name: auth-service
    env_file:
      - .env.docker
    environment:
      - HTTP_ADDR=:5050
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ${AUTH_SERVICE_ROOT}/out/logs:/app/out/logs
    ports:
      - "5050:5050"
    restart: unless-stopped

  postgres:
    image: postgres:16-bookworm
    container_name: auth-service-db
    ports:
      - "5433:5432"
    env_file:
      - .env.docker
    volumes:
      - ${AUTH_SERVICE_ROOT}/out/pgdata:/var/lib/postgresql/data
    restart: always

  postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ${AUTH_SERVICE_ROOT}/migrations:/migrations

  swagger:
    build:
      context: ${AUTH_SERVICE_ROOT}
      dockerfile_inline: |
        FROM golang:1.25.0-alpine
        RUN apk add --no-cache git
        RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
        WORKDIR /code
        ENTRYPOINT ["swag"]
    volumes:
      - ${AUTH_SERVICE_ROOT}:/code
      