basePath: /api/v1
definitions:
  github_com_Andryshazzz_go_pet_internal_core_transport_http_response.ErrorsResponse:
    properties:
      error:
        description: Error contains the technical error details for debugging.
        type: string
      message:
        description: Message contains the human-readable error description.
        type: string
    type: object
  internal_features_auth_transport_http.CreateUserRequest:
    properties:
      full_name:
        example: Ivan Ivanov
        maxLength: 100
        minLength: 2
        type: string
      phone_number:
        example: "+79991118899"
        maxLength: 15
        minLength: 10
        type: string
    required:
    - full_name
    type: object
  internal_features_auth_transport_http.CreateUserResponse:
    properties:
      full_name:
        type: string
      id:
        type: string
      phone_number:
        type: string
    type: object
host: 127.0.0.1:5050
info:
  contact: {}
  description: API for Golang app
  title: Golang app API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Создать нового пользователя в системе
      parameters:
      - description: CreateUser тело запроса
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_features_auth_transport_http.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Успешно созданный пользователь
          schema:
            $ref: '#/definitions/internal_features_auth_transport_http.CreateUserResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/github_com_Andryshazzz_go_pet_internal_core_transport_http_response.ErrorsResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/github_com_Andryshazzz_go_pet_internal_core_transport_http_response.ErrorsResponse'
      summary: Создать пользователя
      tags:
      - Auth
swagger: "2.0"
